### PR TITLE
 error: ‘class at::Context’ has no member named ‘getCurrentCUDAStream…

### PR DESCRIPTION
**Pull request by jiapei100**

### CODE REVIEW

**Comment by clarle** [comment]
For folks trying to get [vid2vid](https://github.com/NVIDIA/vid2vid) running on PyTorch 1.0.0, you need to make the changes in this pull request.

Thanks @jiapei100!

**Comment by MoonBlvd** [comment]
Thank you for your pull request! I'm using pytorch 1.0.0 and CUDA 10. After merging this pull request, I was able to install the three customized layers (correlation, resample2d and channelnorm). However I had to use ```sudo /path/to/virtualenv/python setup.py install``` since I was facing permission denied issue in virtualenv. After those, when I try python main.py in my virtual env, it gives errors: ```resample2d_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at18SparseCUDATensorIdEv```. It seems that the compiled binary is till not usable. Could you please help?

**Comment by fabiopk** [comment]
I am having the exact same problem as @MoonBlvd , with the `resample2d_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at18SparseCUDATensorIdEv`.

Could anyone run this with CUDA 10?

**Comment by Bingmang** [comment]
These commits work for me, thanks!!!

**Comment by awaelchli** [comment]
Why do I get a different message?: 
`undefined symbol _ZN2at19UndefinedTensorImpl10_singletonE`

**Comment by Bingmang** [comment]
No!!! 
It does not work actually! 
The Error was caused by PyTorch version, the code should **never** be running in PyTorch 1.0.0.
And these codes will cause the `undefined symbol` problem in master branch using PyTorch 0.4.1.
So please revert the commit...

**Comment by huangbiubiu** [comment]
Same problem as @MoonBlvd. Is there any workaround?

`undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs`

**Pull request merged**
