### PR TITLE
use static forward and backward methods

### PR DESCRIPTION
**Pull request by bigrobinson**
Use static methods for autograd extension to relieve deprecation warning in Pytorch 1.4.

### CODE REVIEW

**Comment by fitsumreda** [comment]
thanks!

**Comment by bigrobinson** [comment]
Not at all. A big thanks to you guys!

**Comment by suyashhchougule** [comment]
> Use static methods for autograd extension to relieve deprecation warning in Pytorch 1.4.

Hi,  I am struck to this error. I saw you solution. But i am not understanding what is to be done. Could you please elaborate ?

**Comment by suyashhchougule** [comment]
> Use static methods for autograd extension to relieve deprecation warning in Pytorch 1.4.

Hi,I am struck with this error. But , I dont quite understand what has to be done . Could you elaborate more  ?

**Comment by erShoeb** [comment]
RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method.

**Pull request merged**
